### ISSUE TITLE
[Thumbnail] BlackNight.com

### ISSUE THREAD

**Issue by wedebe** [Vascomax/andOTP#10]
BlackNight is a domain registrant in Ireland.

**Name**: BlackNight
**Website**: [blacknight.com](https://blacknight.com)
**Link to SVG or EPS image**:
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:cc="http://web.resource.org/cc/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" version="1.1" baseProfile="full" width="60px" height="60px" viewBox="0 0 60 60" preserveAspectRatio="xMidYMid meet" id="svg_document" style="zoom: 1; background-color: #000000;">
<path d="M14.6,44 l0.7,-1.6 l1,-1.6 l2.2,-2.5 l1.9,-2.1 l0.9,-1.3 l0.7,-1.3 l0.4,-1.5 v-1.3 L22,29.3 l-0.8,-1.1 l-1.8,0.7 L18.2,29 L17,29 l-1.6,-0.4 l-1.6,-0.6 l-0.8,0.4 l-0.8,0.2 l-2.4,0.8 l-0.6,0.5 l-0.4,1.3 l-0.3,0.6 L8,32 L7.5,32 H6.3 l-1.4,-0.2 l-3.5,-1.5 l-0.6,-0.7 l-0.4,-1.1 l-0.2,-1.4 L0,25.4 L0.1,25 L1,24.1 v-0.9 l11.6,-8.8 v-0.9 l0.3,-0.9 l5.6,-3.5 l-0.2,-0.6 l0.1,-0.4 l0.8,-1.6 V6.2 l-1,-0.5 l-1.1,-0.1 l-0.7,0.1 L15,6.1 l-0.4,-0.2 l0.2,-0.6 l0.3,-0.5 l0.7,-1 l0.5,-0.7 l0.6,-0.5 l1.1,-0.7 l1.7,-0.8 l1.4,-0.4 l1.3,0.8 L23,0.3 l1.6,-0.2 L26.2,0 l1.6,0.1 l1.3,0.2 l2,0.8 L31,2.7 l1.2,-1.2 l1.5,0.6 l2,0.9 L37.1,4 l1.9,1.5 l2,2.3 L41,9 l1.5,-0.1 l1,0.7 l1.9,1.8 l1,1.3 l0.8,1.4 l1,2.3 L46.9,18 l1.6,0.4 L49,20 l0.2,1.7 l0.2,2.4 l-0.1,3.4 l-0.3,3.2 l-1.4,0.9 l1.2,0.9 l-0.3,3.8 l-0.7,2.3 L46,41 l-3.1,3 L14.6,44 " id="path1" fill="#ffffff"></path>
</svg>
```

Preview:
https://www.blacknight.com/wp-content/themes/blacknight/favicons/android-icon-192x192.png

**Comment by Vascomax** [comment]
Icon added. Issue closed.  
The new [...F release version](https://github.com/Vascomax/andOTP/releases/tag/v0.9.0.1F-galaxy) will not be uploaded to the Galaxy Store. But you can get it from the [release tab](https://github.com/Vascomax/andOTP/releases/tag/v0.9.0.1F-galaxy) as signed .apk (uses the same signature as the Galaxy Store version, hence can be updated without data loss).
Since Samsung changes their requirements for android developers (basically require to be a business), as hobby developer I will not put up with that and not use the store any longer for android apps.

Do you need it in tizotp for a Tizen watch as well? (maybe I can still use the Galaxy Store for non-android apps)
