### ISSUE TITLE
Wear OS?

### ISSUE THREAD

**Issue by Offerel** [Vascomax/andOTP#7]
Will this work with every Wear OS watch or only with Galaxy Watch 4? Or only with Tizen?

**Comment by Vascomax** [comment]
This phone app comes not bundled with any watch specific app, but in its current release version (v.0.9.0.1B-galaxy) it has built-in support for both: Tizen (bluetooth via SAP) and Wear OS (via native bluetooth implementation).
It has been tested only with GW4 so far, but it should work with any reasonable modern Wear OS watch (API >=26). It only depends on the specific watch app, if it is compatible with your watch. Which one do you have? And which watch application you use?
You can even make your own watch app, since this app only provides the encrypted bluetooth data to a paired watch. And this basic functionality uses no special dependencies so it works even with the oldest watches... However in this case you might be not happy with (decryption) performance and should fork your own andOTP to use a lighter method to work better with your watch app. If you have questions, just let me know. Around the holiday season I might even have some time to answer ;-)
